remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
title: CSCE 606 SaaS Project Details
description: Do you need or want a cloud-based software service, or know of someone who does?  If so, this page is for you!
show_downloads: false
